In [2]:
import pandas as pd
import numpy as np

hmp2_raw = pd.read_csv(
    "../data/raw/HMP2_taxonomic_profiles.tsv.gz",
    sep="\t",
    index_col=0,
    compression="gzip",
    nrows=200,
    usecols=range(0, 50)
)

In [3]:
print(hmp2_raw.shape)
hmp2_raw.head()

(200, 49)

,CSM5FZ4M,CSM5MCUO,CSM5MCVL,CSM5MCVN,CSM5MCW6,CSM5MCWC,CSM5MCWE,CSM5MCWG,CSM5MCWQ,CSM5MCX3,...,CSM67UAM,CSM67UAO,CSM67UAQ,CSM67UAS,CSM67UAU,CSM67UAW,CSM67UAY,CSM67UB1,CSM67UB3,CSM67UB9
#SampleID,,,,,,,,,,,,,,,,,,,,,
k__Archaea,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
k__Archaea|p__Euryarchaeota,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
k__Archaea|p__Euryarchaeota|c__Methanobacteria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
hmp2 = hmp2_raw.T
print(hmp2.shape)

(49, 200)

In [5]:
hmp2_raw = pd.read_csv(
    "../data/raw/HMP2_taxonomic_profiles.tsv.gz",
    sep="\t",
    index_col=0,
    compression="gzip"
)

In [6]:
hmp2_raw.to_pickle("../data/processed/hmp2.pkl")

In [7]:
hmp2.shape

(49, 200)

In [8]:
hmp2_raw = pd.read_csv(
    "../data/raw/HMP2_taxonomic_profiles.tsv.gz",
    sep="\t",
    index_col=0,
    compression="gzip"
)

In [9]:
hmp2 = hmp2_raw.T

In [10]:
print(hmp2.shape)

(1638, 1479)

In [14]:
meta.shape
meta.head()
meta.columns

Index(['Project', 'External ID', 'Participant ID', 'site_sub_coll',
       'data_type', 'week_num', 'date_of_receipt', 'interval_days',
       'visit_num', 'Research Project',
       ...
       'FecalCal received at MGH:', 'Proteomics received at LBNL:',
       'Stool Sample ID:  Tube A  (EtOH)',
       'Sample ID: Tube B (No preservative)',
       'Tube A and B received at Broad:', 'stool_id', 'smoking status',
       'Number years smoked', 'Age when started smoking',
       'How many cigarettes/cigars/etc. do you smoke per day?'],
      dtype='object', length=490)

In [1]:
[c for c in meta.columns if 'diag' in c.lower()]

NameError: name 'meta' is not defined

In [6]:
import pandas as pd
import numpy as np

meta = pd.read_csv("../data/raw/HMP2_metadata.csv", low_memory=False)

In [7]:
[c for c in meta.columns if 'diag' in c.lower()]

['Age at diagnosis',
 'diagnosis',
 'Subject has been diagnosed with indeterminate colitis:',
 'Thyroid disease (uncertain diagnosis, not cancer)',
 'Arthritis (uncertain diagnosis)',
 'Subject has a confirmed diagnosis of IBD:',
 'Subject was diagnosed within the last 6 months:',
 'Age at diagnosis (A)']

In [12]:
meta_wgs = meta[meta['data_type'] == 'metagenomics'].copy()
meta_wgs = meta_wgs.set_index('External ID')

print("\nHMP2 Metadata:")
print(f"  Metagenomics samples: {len(meta_wgs)}")
print(f"  CD:     {(meta_wgs['diagnosis']=='CD').sum()}")
print(f"  UC:     {(meta_wgs['diagnosis']=='UC').sum()}")
print(f"  nonIBD: {(meta_wgs['diagnosis']=='nonIBD').sum()}")
print(f"  Patients: {meta_wgs['Participant ID'].nunique()}")
print(f"  Weeks: {meta_wgs['week_num'].min()} to "
       f"{meta_wgs['week_num'].max()}")

HMP2 Metadata:
  Metagenomics samples: 1638
  CD:     750
  UC:     459
  nonIBD: 429
  Patients: 130
  Weeks: 0.0 to 57.0

In [10]:
meta_wgs['diagnosis'].value_counts()

diagnosis
CD        750
UC        459
nonIBD    429
Name: count, dtype: int64

In [11]:
hmp2 = hmp2_raw.T

matched_ids = hmp2.index.intersection(meta_wgs.index)

print("Matched samples:", len(matched_ids))

NameError: name 'hmp2_raw' is not defined

In [13]:
import pandas as pd

hmp2_raw = pd.read_csv(
    "../data/raw/HMP2_taxonomic_profiles.tsv.gz",
    sep="\t",
    index_col=0,
    compression="gzip"
)

In [14]:
hmp2 = hmp2_raw.T

matched_ids = hmp2.index.intersection(meta_wgs.index)

print("Matched samples:", len(matched_ids))

Matched samples: 1638

In [15]:
cd_samples = meta_wgs[meta_wgs['diagnosis'] == 'CD'].index
uc_samples = meta_wgs[meta_wgs['diagnosis'] == 'UC'].index
healthy_samples = meta_wgs[meta_wgs['diagnosis'] == 'nonIBD'].index

hmp2_cd = hmp2.loc[cd_samples]
hmp2_uc = hmp2.loc[uc_samples]
hmp2_healthy = hmp2.loc[healthy_samples]

print("CD:", hmp2_cd.shape)
print("UC:", hmp2_uc.shape)
print("Healthy:", hmp2_healthy.shape)

CD: (750, 1479)
UC: (459, 1479)
Healthy: (429, 1479)

In [16]:
def filter_rare(df, threshold=0.05):
    keep = (df > 0).mean(axis=0) > threshold
    return df.loc[:, keep]

hmp2_cd = filter_rare(hmp2_cd)
hmp2_uc = filter_rare(hmp2_uc)
hmp2_healthy = filter_rare(hmp2_healthy)

print(hmp2_cd.shape, hmp2_uc.shape, hmp2_healthy.shape)

(750, 463) (459, 461) (429, 472)

In [17]:
import numpy as np

hmp2_cd = np.log1p(hmp2_cd)
hmp2_uc = np.log1p(hmp2_uc)
hmp2_healthy = np.log1p(hmp2_healthy)

In [18]:
common_species = (
    set(hmp2_cd.columns)
    & set(hmp2_uc.columns)
    & set(hmp2_healthy.columns)
)

common_species = list(common_species)

hmp2_cd = hmp2_cd[common_species]
hmp2_uc = hmp2_uc[common_species]
hmp2_healthy = hmp2_healthy[common_species]

print(hmp2_cd.shape, hmp2_uc.shape, hmp2_healthy.shape)

(750, 394) (459, 394) (429, 394)

In [19]:
hmp2_matched = hmp2.loc[matched_ids]
meta_matched = meta_wgs.loc[matched_ids]

In [20]:
print("\nSplitting by diagnosis...")

hmp2_matched = hmp2.loc[matched_ids]
meta_matched = meta_wgs.loc[matched_ids]

cd_idx = meta_matched[meta_matched['diagnosis'] == 'CD'].index
uc_idx = meta_matched[meta_matched['diagnosis'] == 'UC'].index
healthy_idx = meta_matched[meta_matched['diagnosis'] == 'nonIBD'].index

hmp2_cd = hmp2_matched.loc[cd_idx]
hmp2_uc = hmp2_matched.loc[uc_idx]
hmp2_healthy = hmp2_matched.loc[healthy_idx]

print(f"CD samples: {len(hmp2_cd)}")
print(f"UC samples: {len(hmp2_uc)}")
print(f"Healthy samples: {len(hmp2_healthy)}")

Splitting by diagnosis...
CD samples: 750
UC samples: 459
Healthy samples: 429

In [21]:
hmp2_cd.to_csv("../data/processed/CD_raw.csv")
hmp2_uc.to_csv("../data/processed/UC_raw.csv")
hmp2_healthy.to_csv("../data/processed/healthy_raw.csv")

meta_matched.to_csv("../data/processed/HMP2_meta_matched.csv")

print("\n Raw splits saved")

 Raw splits saved

In [22]:
pd.read_csv("../data/processed/CD_raw.csv").head()

,Unnamed: 0,k__Archaea,k__Archaea|p__Euryarchaeota,k__Archaea|p__Euryarchaeota|c__Methanobacteria,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_smithii,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_smithii|t__Methanobrevibacter_smithii_unclassified,k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_unclassified,...,k__Viruses|p__Viruses_noname|c__Viruses_noname|o__Viruses_noname|f__Viruses_noname|g__Viruses_noname,k__Viruses|p__Viruses_noname|c__Viruses_noname|o__Viruses_noname|f__Viruses_noname|g__Viruses_noname|s__Alternanthera_yellow_vein_betasatellite,k__Viruses|p__Viruses_noname|c__Viruses_noname|o__Viruses_noname|f__Viruses_noname|g__Viruses_noname|s__Alternanthera_yellow_vein_betasatellite|t__PRJNA19833,k__Viruses|p__Viruses_noname|c__Viruses_noname|o__Viruses_noname|f__Viruses_noname|g__Viruses_noname|s__Hollyhock_leaf_crumple_virus_satellite_DNA,k__Viruses|p__Viruses_noname|c__Viruses_noname|o__Viruses_noname|f__Viruses_noname|g__Viruses_noname|s__Hollyhock_leaf_crumple_virus_satellite_DNA|t__PRJNA14208,k__Viruses|p__Viruses_noname|c__Viruses_noname|o__Viruses_noname|f__Viruses_noname|g__Viruses_noname|s__Staphylococcus_phage_phi2958PVL,k__Viruses|p__Viruses_noname|c__Viruses_noname|o__Viruses_noname|f__Viruses_noname|g__Viruses_noname|s__Staphylococcus_phage_phi2958PVL|t__PRJNA32173,k__Viruses|p__Viruses_noname|c__Viruses_noname|o__Viruses_noname|f__Viruses_noname|g__Viruses_noname|s__Tomato_begomovirus_satellite_DNA_beta,k__Viruses|p__Viruses_noname|c__Viruses_noname|o__Viruses_noname|f__Viruses_noname|g__Viruses_noname|s__Tomato_begomovirus_satellite_DNA_beta|t__PRJNA14449,unclassified
0,CSM5MCVL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,CSM5MCVN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,CSM5MCW6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,CSM5MCWC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CSM5MCWE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
import pandas as pd
import numpy as np

def preprocess_condition(condition_name, apply_prevalence=0.20):

    print(f"\n{'='*45}")
    print(f"PROCESSING: {condition_name}")
    print('='*45)

    df = pd.read_csv(
        f"../data/processed/{condition_name}_raw.csv",
        index_col=0
    )
    print(f"Loaded: {df.shape}")

    if df.columns.str.contains('s__').any():
        species_cols = df.columns[
            df.columns.str.contains('s__') &
            ~df.columns.str.contains('t__')
        ]
        df = df[species_cols]
        df.columns = df.columns.str.split('s__').str[-1]

    print(f"Species level: {df.shape[1]} species")

    if df.values.max() > 1.0:
        df = df / 100.0

    prev = (df > 0).mean(axis=0)
    df = df.loc[:, prev >= apply_prevalence]
    print(f"After prevalence filter: {df.shape[1]} species")

    df = df.loc[:, df.mean(axis=0) >= 0.0001]
    print(f"After abundance filter: {df.shape[1]} species")

    sums = df.sum(axis=1)
    Q1, Q3 = sums.quantile([0.25, 0.75])
    IQR = Q3 - Q1

    outliers = sums[
        (sums < Q1 - 3*IQR) | (sums > Q3 + 3*IQR)
    ]

    df = df.drop(index=outliers.index)
    print(f"After outlier removal: {df.shape[0]} samples")

    df_norm = df.div(df.sum(axis=1), axis=0)

    df_pseudo = df_norm + 1e-6
    log_df = np.log(df_pseudo)
    df_clr = log_df.sub(log_df.mean(axis=1), axis=0)

    df_norm.to_csv(f"../data/processed/{condition_name}_normalized.csv")
    df_clr.to_csv(f"../data/processed/{condition_name}_CLR.csv")

    print("Saved ")

    return df_norm, df_clr

In [38]:
cd_norm, cd_clr = preprocess_condition("CD")
uc_norm, uc_clr = preprocess_condition("UC")
healthy_norm, healthy_clr = preprocess_condition("healthy")

=============================================
PROCESSING: CD
=============================================
Loaded: (750, 1479)
Species level: 572 species
After prevalence filter: 94 species
After abundance filter: 92 species
After outlier removal: 738 samples
Saved

=============================================
PROCESSING: UC
=============================================
Loaded: (459, 1479)
Species level: 572 species
After prevalence filter: 93 species
After abundance filter: 90 species
After outlier removal: 447 samples
Saved

=============================================
PROCESSING: healthy
=============================================
Loaded: (429, 1479)
Species level: 572 species
After prevalence filter: 101 species
After abundance filter: 98 species
After outlier removal: 419 samples
Saved

In [39]:
common_species = set(cd_norm.columns) & set(uc_norm.columns) & set(healthy_norm.columns)

print("Common species:", len(common_species))

cd_norm = cd_norm[list(common_species)]
uc_norm = uc_norm[list(common_species)]
healthy_norm = healthy_norm[list(common_species)]

cd_norm.to_csv("../data/processed/CD_aligned.csv")
uc_norm.to_csv("../data/processed/UC_aligned.csv")
healthy_norm.to_csv("../data/processed/healthy_aligned.csv")

Common species: 84